"""Validate generated Phase 2 artifacts without deploying Azure resources."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PARAMETERS_PATH = ROOT / "infra" / "main.parameters.json"
MANIFEST_PATH = ROOT / "config" / "poc-created-resources.json"
SEARCH_OBJECTS_PATH = ROOT / "config" / "search-objects.json"
PLAN_PATH = ROOT / "deployment-plan.json"
EXPECTED_RESOURCE_GROUP = "rg-tjx-retail-search-poc-greenfield"
EXPECTED_RESOURCE_KINDS = {
    "applicationManagedIdentity",
    "blobContainer",
    "cosmosAccount",
    "cosmosSqlContainer",
    "cosmosSqlDatabase",
    "openAIAccount",
    "openAIEmbeddingDeployment",
    "resourceGroup",
    "roleAssignments",
    "searchDataSource",
    "searchIndexer",
    "searchIndex",
    "searchService",
    "searchSharedPrivateLink",
    "searchSkillset",
    "storageAccount",
}
FORBIDDEN_CORE_NAME_PARAMETERS = {
    "applicationPrincipalId",
    "cosmosAccountName",
    "createCosmosAccount",
    "openAIAccountName",
    "searchServiceName",
    "storageAccountName",
}


class ValidationError(RuntimeError):
    """Raised when a generated artifact violates a Phase 2 guardrail."""


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValidationError(f"Unable to load {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValidationError(f"Expected a JSON object in {path}")
    return value


def parameter_values(document: dict[str, Any]) -> dict[str, Any]:
    return {
        name: item.get("value")
        for name, item in document.get("parameters", {}).items()
        if isinstance(item, dict)
    }


def validate_parameters(parameters: dict[str, Any]) -> None:
    values = parameter_values(parameters)
    if values.get("resourceGroupName") != EXPECTED_RESOURCE_GROUP:
        raise ValidationError(
            "The template does not create the approved greenfield resource group."
        )
    forbidden = FORBIDDEN_CORE_NAME_PARAMETERS.intersection(values)
    if forbidden:
        raise ValidationError(
            f"Core resource names must be generated by Bicep: {sorted(forbidden)}"
        )
    for name in ("embeddingModelName", "embeddingModelVersion", "embeddingDeploymentName"):
        if not values.get(name):
            raise ValidationError(f"{name} must be explicit.")
    for name in ("embeddingCapacity", "embeddingDimensions"):
        if not isinstance(values.get(name), int) or values[name] < 1:
            raise ValidationError(f"{name} must be a positive integer.")


def validate_manifest(manifest: dict[str, Any]) -> None:
    deployment_status = manifest.get("deploymentStatus")
    if deployment_status not in {"planned-not-deployed", "deployed-and-verified"}:
        raise ValidationError("Manifest has an invalid Phase 2 deployment status.")
    if manifest.get("resourceGroup") != EXPECTED_RESOURCE_GROUP:
        raise ValidationError("Manifest resource group does not match the greenfield plan.")
    if manifest.get("reusedResources"):
        raise ValidationError("A greenfield deployment cannot contain reused resources.")
    resources = manifest.get("resources", [])
    if not resources or any(item.get("ownedByPoc") is not True for item in resources):
        raise ValidationError("Every manifest resource must be explicitly POC-owned.")
    if deployment_status == "planned-not-deployed":
        if any(item.get("status") != "planned" for item in resources):
            raise ValidationError("Planned manifest resources must remain marked planned.")
    elif any(not str(item.get("status", "")).startswith("deployed") for item in resources):
        raise ValidationError("Every verified manifest resource must be marked deployed.")
    kinds = {item.get("kind") for item in resources}
    if kinds != EXPECTED_RESOURCE_KINDS:
        raise ValidationError("Manifest does not enumerate the complete greenfield resource graph.")


def validate_search_objects(config: dict[str, Any]) -> None:
    if config.get("searchEndpoint") != "${AZURE_SEARCH_ENDPOINT}":
        raise ValidationError("Search endpoint must be resolved from azd deployment outputs.")
    objects = config.get("objects", [])
    kinds = {item.get("kind") for item in objects}
    if kinds != {"indexes", "datasources", "skillsets", "indexers"}:
        raise ValidationError("Search configuration must contain the complete object graph.")
    serialized = json.dumps(config)
    for required in (
        "${AZURE_COSMOS_RESOURCE_ID}",
        "${AZURE_EMBEDDING_DEPLOYMENT}",
        "${AZURE_EMBEDDING_DIMENSIONS}",
        "${AZURE_EMBEDDING_MODEL}",
        "${AZURE_OPENAI_ENDPOINT}",
        "IdentityAuthType=AccessToken",
        "executionEnvironment",
        "descriptionVector",
    ):
        if required not in serialized:
            raise ValidationError(f"Search configuration is missing {required}.")
    if "apiKey" in serialized or "blockedObjects" in config:
        raise ValidationError("Search configuration contains a local-auth or blocked placeholder.")


def validate_plan(plan: dict[str, Any]) -> None:
    if plan.get("strategy") != "greenfield" or plan.get("reuseExistingResources") is not False:
        raise ValidationError("Deployment plan must remain strictly greenfield.")
    approval = plan.get("approval", {})
    if approval.get("implementationApproved") is not True:
        raise ValidationError("Implementation approval has not been recorded.")
    deployment_approved = approval.get("deploymentApproved")
    expected_approval = plan.get("status") in {
        "deployment-approved",
        "deployed",
        "phase-2-deployed-and-verified",
    }
    if deployment_approved is not expected_approval:
        raise ValidationError("Deployment approval is inconsistent with the plan status.")


def validate_bicep_source() -> None:
    source = (ROOT / "infra" / "main.bicep").read_text(encoding="utf-8")
    for forbidden in FORBIDDEN_CORE_NAME_PARAMETERS:
        if f"param {forbidden} " in source:
            raise ValidationError(f"Forbidden reuse-oriented input remains: {forbidden}")
    module_sources = "\n".join(
        path.read_text(encoding="utf-8") for path in (ROOT / "infra" / "modules").glob("*.bicep")
    )
    for required in ("disableLocalAuth: true", "allowSharedKeyAccess: false"):
        if required not in module_sources:
            raise ValidationError(f"Entra-only guardrail is missing: {required}")


def compile_bicep() -> None:
    az = shutil.which("az")
    if az is None:
        raise ValidationError("Azure CLI is required to compile Bicep.")
    uses_command_shell = Path(az).suffix.casefold() in {".cmd", ".bat"}
    completed = subprocess.run(
        [az, "bicep", "build", "--file", str(ROOT / "infra" / "main.bicep"), "--stdout"],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        shell=uses_command_shell,
    )
    if completed.returncode != 0:
        raise ValidationError(completed.stderr.strip() or "Bicep compilation failed.")


def main() -> int:
    try:
        validate_parameters(load_json(PARAMETERS_PATH))
        validate_manifest(load_json(MANIFEST_PATH))
        validate_search_objects(load_json(SEARCH_OBJECTS_PATH))
        validate_plan(load_json(PLAN_PATH))
        validate_bicep_source()
        compile_bicep()
        print("PASS: Phase 2 artifacts are internally consistent.")
        return 0
    except ValidationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())